from pyrogram import Client
from pyrogram.errors import UserIsBot

# USAGE :
## Run python3 genStringSession.py
## Or
## Run python genStringSession.py
## In Terminal of Heroku or Locally

print("<<<<<<<< Pyrogram StringSession V2 >>>>>>>>\n")

with Client(
    "Tele-LeechX",
    input("Enter Telegram APP ID: "),
    input("Enter Telegram API HASH: "),
    in_memory=True
) as userBot:
    print("\nProcessing...")
    donestr = "sent to Saved Messages !!"
    try:
        userBot.send_message(
            "me",
            f"#TeleLeechX #PYROGRAM_STRING_SESSION\n\n```{userBot.export_session_string()}```\n\n✨ __Generated By__ https://github.com/5MysterySD/Tele-LeechX/genStringSession.py",
        )
    except UserIsBot:
        donestr = "Successfully Printed !!"
        print(userBot.export_session_string())
    print(f"Done !!, String Session has been {donestr}")

